rootProject.name = 'evidence-poc'

include ':backend', ':backend-domain', ':backend-api', ':backend-persistent'
project(':backend').projectDir = file('apps/backend')
project(':backend-domain').projectDir = file('libs/backend/domain')
project(':backend-api').projectDir = file('libs/backend/api')
project(':backend-persistent').projectDir = file('libs/backend/persistent')
