#!/usr/bin/env python3
"""Render deterministic business-pattern documentation from FM Schema v3 YAML."""

from __future__ import annotations

import argparse
import os
import sys
import tempfile
from pathlib import Path
from typing import Any

from fm_model import LoadedModel, load_model, validate_model


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render FM Schema v3 business patterns as Markdown."
    )
    parser.add_argument(
        "model_dir", help="Directory containing model.yaml and FM shards"
    )
    parser.add_argument("--output", required=True, help="Output Markdown path")
    return parser.parse_args()


def bullet_refs(label: str, refs: list[Any]) -> list[str]:
    rendered = ", ".join(f"`{ref}`" for ref in refs) if refs else "—"
    return [f"- {label}: {rendered}"]


def render_business_patterns(model: LoadedModel) -> str:
    model_name = str(
        (model.manifest or {}).get("name") or (model.manifest or {}).get("id") or "FM"
    )
    lines = [
        "<!-- Generated by build_fm_business_patterns.py; edit business-patterns/*.yaml instead. -->",
        "",
        f"# {model_name} · 业务模式",
        "",
    ]
    patterns = sorted(model.business_patterns, key=lambda item: str(item.get("id", "")))
    if not patterns:
        lines.extend(["当前模型尚未提取候选业务模式。", ""])
        return "\n".join(lines)

    for pattern in patterns:
        review = pattern.get("stakeholderReview") or {}
        lines.extend(
            [
                f"## {pattern.get('label')} (`{pattern.get('id')}`)",
                "",
                f"- 复用状态：`{pattern.get('reuseStatus')}`",
                "- 业务目标："
                + ", ".join(f"`{goal}`" for goal in pattern.get("businessGoals") or []),
                f"- 运营不变量：{pattern.get('operationInvariant')}",
                f"- 领域中立主张：{pattern.get('domainNeutralClaim')}",
            ]
        )
        lines.extend(bullet_refs("业务脊梁", pattern.get("businessSpineRefs") or []))
        lines.extend(bullet_refs("不变量引用", pattern.get("invariantRefs") or []))
        lines.extend(bullet_refs("变化点", pattern.get("variationPointRefs") or []))
        lines.extend(bullet_refs("领域输入", pattern.get("domainInputRefs") or []))
        lines.extend(
            bullet_refs(
                "合同上下文证据",
                pattern.get("supportedByContractContextRefs") or [],
            )
        )
        lines.extend(
            bullet_refs("领域案例", pattern.get("domainExampleContextRefs") or [])
        )
        review_line = f"- 业务方评审：`{review.get('status', 'pending')}`"
        if review.get("reviewer"):
            review_line += f"，{review.get('reviewer')} @ {review.get('reviewedAt')}"
        lines.extend([review_line, ""])
        if pattern.get("notes"):
            lines.extend([str(pattern["notes"]), ""])
    return "\n".join(lines)


def write_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", dir=path.parent
    )
    temporary_path = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as file:
            file.write(content)
        temporary_path.replace(path)
    except Exception:
        temporary_path.unlink(missing_ok=True)
        raise


def main() -> int:
    args = parse_args()
    model = load_model(Path(args.model_dir))
    errors = validate_model(model)
    if errors:
        print(
            "Business-pattern rendering aborted because validation failed:",
            file=sys.stderr,
        )
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1
    output = Path(args.output)
    content = render_business_patterns(model)
    write_atomic(output, content)
    print(f"Rendered FM Schema v3 business patterns: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
